AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 128

Resources:
  PaymentLinksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub payment-links-${AWS::StackName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.main.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref PaymentLinksTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PaymentLinksTable
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: "HTTP API endpoint"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  TableName:
    Description: "DynamoDB table name"
    Value: !Ref PaymentLinksTable
